export const BUILDER = {
  ACCESS_ITEM_LOGIN_TAG_TOOLTIP: 'ACCESS_ITEM_LOGIN_TAG_TOOLTIP',
  ACCESS_ITEM_LOGIN_TAG: 'ACCESS_ITEM_LOGIN_TAG',
  ACCESS_PUBLIC_TAG_TOOLTIP: 'ACCESS_PUBLIC_TAG_TOOLTIP',
  ACCESS_PUBLIC_TAG: 'ACCESS_PUBLIC_TAG',
  ACCESS_TITLE: 'ACCESS_TITLE',
  HOME_SHOW_ONLY_CREATED_BY_ME: 'HOME_SHOW_ONLY_CREATED_BY_ME',
  ANALYTICS_DASHBOARD_LABEL: 'ANALYTICS_DASHBOARD_LABEL',
  AVATAR_DEFAULT_ALT: 'AVATAR_DEFAULT_ALT',
  COLLAPSE_ITEM_COLLAPSE_TEXT: 'COLLAPSE_ITEM_COLLAPSE_TEXT',
  COLLAPSE_ITEM_UNCOLLAPSE_TEXT: 'COLLAPSE_ITEM_UNCOLLAPSE_TEXT',
  CONFIRM_BUTTON: 'CONFIRM_BUTTON',
  COPY_ITEM_MODAL_TITLE: 'COPY_ITEM_MODAL_TITLE',
  COPY_BUTTON: 'COPY_BUTTON',
  ITEM_TEMPLATE_SELECTION_MODAL_TITLE: 'ITEM_TEMPLATE_SELECTION_MODAL_TITLE',
  ITEM_TEMPLATE_SELECTION_BUTTON: 'ITEM_TEMPLATE_SELECTION_BUTTON',
  CREATE_ITEM_ADD_BUTTON: 'CREATE_ITEM_ADD_BUTTON',
  CREATE_ITEM_APP_TITLE: 'CREATE_ITEM_APP_TITLE',
  CREATE_ITEM_DOCUMENT_TITLE: 'CREATE_ITEM_DOCUMENT_TITLE',
  CREATE_ITEM_FOLDER_TITLE: 'CREATE_ITEM_FOLDER_TITLE',
  CREATE_ITEM_LINK_INVALID_LINK_ERROR: 'CREATE_ITEM_LINK_INVALID_LINK_ERROR',
  CREATE_ITEM_LINK_LABEL: 'CREATE_ITEM_LINK_LABEL',
  CREATE_ITEM_LINK_TITLE: 'CREATE_ITEM_LINK_TITLE',
  CREATE_ITEM_LINK_TYPE_TITLE: 'CREATE_ITEM_LINK_TYPE_TITLE',
  CREATE_ITEM_LINK_TYPE_HELPER_TEXT: 'CREATE_ITEM_LINK_TYPE_HELPER_TEXT',
  CREATE_ITEM_LINK_EMBED_TITLE: 'CREATE_ITEM_LINK_EMBED_TITLE',
  CREATE_ITEM_LINK_EMBED_HELPER_TEXT: 'CREATE_ITEM_LINK_EMBED_HELPER_TEXT',
  CREATE_ITEM_NEW_FOLDER_TITLE: 'CREATE_ITEM_NEW_FOLDER_TITLE',
  CREATE_NEW_ITEM_APP_TITLE: 'CREATE_NEW_ITEM_APP_TITLE',
  CREATE_NEW_ITEM_APP_URL_LABEL: 'CREATE_NEW_ITEM_APP_URL_LABEL',
  CREATE_NEW_ITEM_DOCUMENT_TITLE: 'CREATE_NEW_ITEM_DOCUMENT_TITLE',
  CREATE_NEW_ITEM_ETHERPAD_INFORMATIONS:
    'CREATE_NEW_ITEM_ETHERPAD_INFORMATIONS',
  CREATE_NEW_ITEM_ETHERPAD_LABEL: 'CREATE_NEW_ITEM_ETHERPAD_LABEL',
  CREATE_NEW_ITEM_ETHERPAD_TITLE: 'CREATE_NEW_ITEM_ETHERPAD_TITLE',
  CREATE_NEW_ITEM_NAME_LABEL: 'CREATE_NEW_ITEM_NAME_LABEL',
  CREATE_SHORTCUT_BUTTON: 'CREATE_SHORTCUT_BUTTON',
  CREATE_SHORTCUT_DEFAULT_NAME: 'CREATE_SHORTCUT_DEFAULT_NAME',
  CREATE_SHORTCUT_MODAL_TITLE: 'CREATE_SHORTCUT_MODAL_TITLE',
  CROP_IMAGE_MODAL_CONTENT_TEXT: 'CROP_IMAGE_MODAL_CONTENT_TEXT',
  CROP_IMAGE_MODAL_TITLE: 'CROP_IMAGE_MODAL_TITLE',
  CROP_IMAGE_MODAL_IMAGE_ALT_TEXT: 'CROP_IMAGE_MODAL_IMAGE_ALT_TEXT',
  CROP_IMAGE_MODAL_UNEXPECTED_ERROR: 'CROP_IMAGE_MODAL_UNEXPECTED_ERROR',
  DELETE_BUTTON: 'DELETE_BUTTON',
  DELETE_ITEM_MODAL_CONFIRM_BUTTON: 'DELETE_ITEM_MODAL_CONFIRM_BUTTON',
  DELETE_ITEM_MODAL_CONTENT: 'DELETE_ITEM_MODAL_CONTENT',
  DELETE_ITEM_MODAL_TITLE: 'DELETE_ITEM_MODAL_TITLE',
  DOCUMENT_FLAVOR_SELECT_LABEL: 'DOCUMENT_FLAVOR_SELECT_LABEL',
  DOCUMENT_FLAVOR_ERROR: 'DOCUMENT_FLAVOR_ERROR',
  DOCUMENT_FLAVOR_INFO: 'DOCUMENT_FLAVOR_INFO',
  DOCUMENT_FLAVOR_NAME: 'DOCUMENT_FLAVOR_NAME',
  DOCUMENT_FLAVOR_SUCCESS: 'DOCUMENT_FLAVOR_SUCCESS',
  DOCUMENT_FLAVOR_WARNING: 'DOCUMENT_FLAVOR_WARNING',
  DOCUMENT_FLAVOR_NONE: 'DOCUMENT_FLAVOR_NONE',
  DOWNLOAD_ITEM_BUTTON: 'DOWNLOAD_ITEM_BUTTON',
  DOCUMENT_EDITOR_MODE_RICH_TEXT: 'DOCUMENT_EDITOR_MODE_RICH_TEXT',
  DOCUMENT_EDITOR_MODE_RAW: 'DOCUMENT_EDITOR_MODE_RAW',
  DOCUMENT_EDITOR_MODE_ARIA_LABEL: 'DOCUMENT_EDITOR_MODE_ARIA_LABEL',
  DROP_DOWN_PLACEHOLDER: 'DROP_DOWN_PLACEHOLDER',
  DROPZONE_HELPER_TEXT: 'DROPZONE_HELPER_TEXT',
  DROPZONE_HELPER_LIMIT_REMINDER_TEXT: 'DROPZONE_HELPER_LIMIT_REMINDER_TEXT',
  DROPZONE_HELPER_ACTION: 'DROPZONE_HELPER_ACTION',
  DROPZONE_HELPER_OPTIONAL_ACTION_TEXT: 'DROPZONE_HELPER_OPTIONAL_ACTION_TEXT',
  DESCRIPTION_LABEL: 'DESCRIPTION_LABEL',
  EDIT_BUTTON_TOOLTIP: 'EDIT_BUTTON_TOOLTIP',
  EDIT_FOLDER_DESCRIPTION_PLACEHOLDER: 'EDIT_FOLDER_DESCRIPTION_PLACEHOLDER',
  EDIT_ITEM_BUTTON: 'EDIT_ITEM_BUTTON',
  EDIT_ITEM_ERROR_MESSAGE: 'EDIT_ITEM_ERROR_MESSAGE',
  EDIT_ITEM_MODAL_TITLE: 'EDIT_ITEM_MODAL_TITLE',
  EDIT_ITEM_IMAGE_ALT_TEXT_LABEL: 'EDIT_ITEM_IMAGE_ALT_TEXT_LABEL',
  EMPTY_FOLDER_MESSAGE: 'EMPTY_FOLDER_MESSAGE',
  ERROR_MESSAGE: 'ERROR_MESSAGE',
  BOOKMARKED_ITEM_ADD_TEXT: 'BOOKMARKED_ITEM_ADD_TEXT',
  BOOKMARKED_ITEM_REMOVE_TEXT: 'BOOKMARKED_ITEM_REMOVE_TEXT',
  BOOKMARKED_ITEMS_TITLE: 'BOOKMARKED_ITEMS_TITLE',
  FLAG_ITEM_BUTTON: 'FLAG_ITEM_BUTTON',
  FLAG_ITEM_MODAL_TITLE: 'FLAG_ITEM_MODAL_TITLE',
  HIDE_ITEM_HIDDEN_PARENT_INFORMATION: 'HIDE_ITEM_HIDDEN_PARENT_INFORMATION',
  HIDE_ITEM_SETTING_DESCRIPTION_ENABLED:
    'HIDE_ITEM_SETTING_DESCRIPTION_ENABLED',
  HIDE_ITEM_SETTING_DESCRIPTION_DISABLED:
    'HIDE_ITEM_SETTING_DESCRIPTION_DISABLED',
  HIDE_ITEM_SETTING_TITLE: 'HIDE_ITEM_SETTING_TITLE',
  HIDE_ITEM_HIDE_TEXT: 'HIDE_ITEM_HIDE_TEXT',
  HIDE_ITEM_SHOW_TEXT: 'HIDE_ITEM_SHOW_TEXT',
  HOME_TITLE: 'HOME_TITLE',
  IMPORT_H5P_INFORMATIONS: 'IMPORT_H5P_INFORMATIONS',
  IMPORT_H5P_LIMITATIONS_TEXT: 'IMPORT_H5P_LIMITATIONS_TEXT',
  IMPORT_H5P_TITLE: 'IMPORT_H5P_TITLE',
  IMPORT_H5P_WARNING: 'IMPORT_H5P_WARNING',
  IMPORT_ZIP_INFORMATION: 'IMPORT_ZIP_INFORMATION',
  IMPORT_ZIP_LIMITATIONS_TEXT: 'IMPORT_ZIP_LIMITATIONS_TEXT',
  IMPORT_ZIP_TITLE: 'IMPORT_ZIP_TITLE',
  IMPORT_ZIP_WARNING: 'IMPORT_ZIP_WARNING',
  IMPORT_ZIP_BUTTON: 'IMPORT_ZIP_BUTTON',
  INVITATIONS_TABLE_ACTIONS_HEADER: 'INVITATIONS_TABLE_ACTIONS_HEADER',

  MOVE_BUTTON: 'MOVE_BUTTON',

  PIN_ITEM_PIN_TEXT: 'PIN_ITEM_PIN_TEXT',
  PIN_ITEM_UNPIN_TEXT: 'PIN_ITEM_UNPIN_TEXT',
  PLAY_BUTTON_TOOLTIP: 'PLAY_BUTTON_TOOLTIP',

  LIBRARY_SETTINGS_BUTTON_TITLE: 'LIBRARY_SETTINGS_BUTTON_TITLE',
  RECYCLE_ITEM_BUTTON: 'RECYCLE_ITEM_BUTTON',
  TRASH_NO_ITEM: 'TRASH_NO_ITEM',
  BOOKMARKS_NO_ITEM: 'BOOKMARKS_NO_ITEM',
  BOOKMARKS_NO_ITEM_SEARCH: 'BOOKMARKS_NO_ITEM_SEARCH',
  RESTORE_ITEM_BUTTON: 'RESTORE_ITEM_BUTTON',
  SHARE_ITEM_BUTTON: 'SHARE_ITEM_BUTTON',
  ITEM_METADATA_CREATOR_TITLE: 'ITEM_METADATA_CREATOR_TITLE',
  ITEM_METADATA_TYPE_TITLE: 'ITEM_METADATA_TYPE_TITLE',
  USER_SWITCH_PROFILE_BUTTON: 'USER_SWITCH_PROFILE_BUTTON',

  RECYCLE_BIN_TITLE: 'RECYCLE_BIN_TITLE',

  SETTINGS_COLLAPSE_LABEL: 'SETTINGS_COLLAPSE_LABEL',
  SETTINGS_PIN_ITEM_LABEL: 'SETTINGS_PIN_ITEM_LABEL',
  SETTINGS_SHOW_CHAT_LABEL: 'SETTINGS_SHOW_CHAT_LABEL',
  SETTINGS_RESIZE_LABEL: 'SETTINGS_RESIZE_LABEL',
  SETTINGS_MAX_WIDTH_LABEL: 'SETTINGS_MAX_WIDTH_LABEL',
  SETTINGS_ALIGNMENT_LABEL: 'SETTINGS_ALIGNMENT_LABEL',
  SETTINGS_ALIGNMENT_HELPER: 'SETTINGS_ALIGNMENT_HELPER',
  SETTINGS_ALIGNMENT_ARIA_LABEL: 'SETTINGS_ALIGNMENT_ARIA_LABEL',
  SETTINGS_ALIGNMENT_CENTER_ARIA_LABEL: 'SETTINGS_ALIGNMENT_CENTER_ARIA_LABEL',
  SETTINGS_ALIGNMENT_LEFT_ARIA_LABEL: 'SETTINGS_ALIGNMENT_LEFT_ARIA_LABEL',
  SETTINGS_ALIGNMENT_RIGHT_ARIA_LABEL: 'SETTINGS_ALIGNMENT_RIGHT_ARIA_LABEL',
  SETTINGS_TITLE: 'SETTINGS_TITLE',
  SETTINGS_COLLAPSE_FOLDER_INFORMATION: 'SETTINGS_COLLAPSE_FOLDER_INFORMATION',

  LIBRARY_SETTINGS_INFORMATION: 'LIBRARY_SETTINGS_INFORMATION',
  LIBRARY_SETTINGS_TITLE: 'LIBRARY_SETTINGS_TITLE',
  LIBRARY_SETTINGS_PREVIEW_TITLE: 'LIBRARY_SETTINGS_PREVIEW_TITLE',
  LIBRARY_SETTINGS_PREVIEW_DESCRIPTION: 'LIBRARY_SETTINGS_PREVIEW_DESCRIPTION',
  LIBRARY_SETTINGS_VALIDATION_TITLE: 'LIBRARY_SETTINGS_VALIDATION_TITLE',
  LIBRARY_SETTINGS_VISIBILITY_CHANGE_BUTTON:
    'LIBRARY_SETTINGS_VISIBILITY_CHANGE_BUTTON',
  LIBRARY_SETTINGS_VIEW_LIBRARY_BUTTON: 'LIBRARY_SETTINGS_VIEW_LIBRARY_BUTTON',
  LIBRARY_SETTINGS_RETRY_BUTTON: 'LIBRARY_SETTINGS_RETRY_BUTTON',
  LIBRARY_SETTINGS_VALIDATION_STATUS_OUTDATED:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_OUTDATED',
  LIBRARY_SETTINGS_ITEM_DESCRIPTION_LABEL:
    'LIBRARY_SETTINGS_ITEM_DESCRIPTION_LABEL',
  LIBRARY_SETTINGS_ITEM_DESCRIPTION_MISSING_WARNING:
    'LIBRARY_SETTINGS_ITEM_DESCRIPTION_MISSING_WARNING',
  LIBRARY_SETTINGS_ITEM_NO_DESCRIPTION: 'LIBRARY_SETTINGS_ITEM_NO_DESCRIPTION',
  LIBRARY_SETTINGS_THUMBNAIL_MISSING_WARNING:
    'LIBRARY_SETTINGS_THUMBNAIL_MISSING_WARNING',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_LOADING:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_LOADING',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_PUBLISHED:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_PUBLISHED',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_PUBLISHED_CHILDREN:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_PUBLISHED_CHILDREN',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_PENDING:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_PENDING',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_READY_TO_PUBLISH:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_READY_TO_PUBLISH',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_NOT_PUBLIC:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_NOT_PUBLIC',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_INVALID:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_INVALID',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_OUTDATED:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_OUTDATED',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_UNPUBLISHED:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_UNPUBLISHED',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_UNKOWN:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_UNKOWN',
  LIBRARY_SETTINGS_PUBLICATION_STATUS_TYPE_NOT_ALLOWED:
    'LIBRARY_SETTINGS_PUBLICATION_STATUS_TYPE_NOT_ALLOWED',
  LIBRARY_SETTINGS_ITEM_NAME_CANNOT_BE_EMPTY:
    'LIBRARY_SETTINGS_ITEM_NAME_CANNOT_BE_EMPTY',

  PUBLIC_VISIBILITY_MODAL_TITLE: 'PUBLIC_VISIBILITY_MODAL_TITLE',
  PUBLIC_VISIBILITY_MODAL_DESCRIPTION: 'PUBLIC_VISIBILITY_MODAL_DESCRIPTION',
  PUBLIC_VISIBILITY_MODAL_VALIDATE_BUTTON:
    'PUBLIC_VISIBILITY_MODAL_VALIDATE_BUTTON',

  UPDATE_VISIBILITY_MODAL_TITLE: 'UPDATE_VISIBILITY_MODAL_TITLE',
  UPDATE_VISIBILITY_MODAL_DESCRIPTION: 'UPDATE_VISIBILITY_MODAL_DESCRIPTION',
  UPDATE_VISIBILITY_MODAL_VALIDATE_BUTTON:
    'UPDATE_VISIBILITY_MODAL_VALIDATE_BUTTON',

  PUBLISHED_ITEMS_TITLE: 'PUBLISHED_ITEMS_TITLE',

  SHARE_ITEM_CSV_IMPORT_MODAL_TITLE: 'SHARE_ITEM_CSV_IMPORT_MODAL_TITLE',
  SHARE_ITEM_CSV_IMPORT_SUCCESS_MESSAGE:
    'SHARE_ITEM_CSV_IMPORT_SUCCESS_MESSAGE',
  SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT: 'SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT',
  SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT_GROUP_COLUMN_DETECTED:
    'SHARE_ITEM_CSV_IMPORT_MODAL_CONTENT_GROUP_COLUMN_DETECTED',

  SHARE_ITEM_CSV_IMPORT_INPUT_BUTTON: 'SHARE_ITEM_CSV_IMPORT_INPUT_BUTTON',
  SHARE_ITEM_CSV_IMPORT_SELECTED_TEMPLATE_CAPTION:
    'SHARE_ITEM_CSV_IMPORT_SELECTED_TEMPLATE_CAPTION',
  INVITATION_SUMMARY_GROUP_TITLE: 'INVITATION_SUMMARY_GROUP_TITLE',
  SELECT_TEMPLATE_INPUT_BUTTON: 'SELECT_TEMPLATE_INPUT_BUTTON',
  IMPORT_CSV_SUCCESS_TITLE: 'IMPORT_CSV_SUCCESS_TITLE',
  IMPORT_CSV_SUCCESS_TEXT: 'IMPORT_CSV_SUCCESS_TEXT',
  IMPORT_CSV_ERROR_TITLE: 'IMPORT_CSV_ERROR_TITLE',

  SHARE_ITEM_CSV_IMPORT_ERROR_MESSAGE: 'SHARE_ITEM_CSV_IMPORT_ERROR_MESSAGE',
  SHARE_ITEM_CSV_IMPORT_ERROR_MISSING_COLUMN:
    'SHARE_ITEM_CSV_IMPORT_ERROR_MISSING_COLUMN',
  SHARE_ITEM_FORM_EMAIL_LABEL: 'SHARE_ITEM_FORM_EMAIL_LABEL',
  SHARE_ITEM_FORM_CONFIRM_BUTTON: 'SHARE_ITEM_FORM_CONFIRM_BUTTON',
  SHARE_ITEM_FORM_TITLE: 'SHARE_ITEM_FORM_TITLE',
  SHARE_ITEM_FORM_INVITATION_TOOLTIP: 'SHARE_ITEM_FORM_INVITATION_TOOLTIP',
  SHARE_ITEM_CSV_SUMMARY_GROUP_TITLE: 'SHARE_ITEM_CSV_SUMMARY_GROUP_TITLE',
  SHARE_ITEM_CSV_SUMMARY_MODIFYING_EXISTING:
    'SHARE_ITEM_CSV_SUMMARY_MODIFYING_EXISTING',

  SHARE_ITEM_FORM_INVITATION_EMAIL_EXISTS_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_EMAIL_EXISTS_MESSAGE',
  SHARE_ITEM_FORM_ALREADY_HAVE_MEMBERSHIP_MESSAGE:
    'SHARE_ITEM_FORM_ALREADY_HAVE_MEMBERSHIP_MESSAGE',
  SHARE_ITEM_FORM_INVITATION_INVALID_EMAIL_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_INVALID_EMAIL_MESSAGE',
  SHARE_ITEM_FORM_INVITATION_EMPTY_EMAIL_MESSAGE:
    'SHARE_ITEM_FORM_INVITATION_EMPTY_EMAIL_MESSAGE',
  INVITATIONS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP:
    'INVITATIONS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP',
  ITEM_CATEGORIES_CONTAINER_TITLE: 'ITEM_CATEGORIES_CONTAINER_TITLE',
  ITEM_CATEGORIES_CONTAINER_MISSING_WARNING:
    'ITEM_CATEGORIES_CONTAINER_MISSING_WARNING',
  ITEM_CATEGORIES_CONTAINER_EMPTY_BUTTON:
    'ITEM_CATEGORIES_CONTAINER_EMPTY_BUTTON',
  ITEM_LANGUAGE_CONTAINER_TITLE: 'ITEM_LANGUAGE_CONTAINER_TITLE',
  ITEM_LANGUAGE_DESCRIPTION: 'ITEM_LANGUAGE_DESCRIPTION',
  ITEM_LANGUAGE_DESCRIPTION_LIMITATION: 'ITEM_LANGUAGE_DESCRIPTION_LIMITATION',
  ITEM_LICENSE_CONTAINER_TITLE: 'ITEM_LICENSE_CONTAINER_TITLE',
  ITEM_LICENSE_CONTAINER_MISSING_WARNING:
    'ITEM_LICENSE_CONTAINER_MISSING_WARNING',
  ITEM_LICENSE_CONTAINER_EMPTY_BUTTON: 'ITEM_LICENSE_CONTAINER_EMPTY_BUTTON',
  ITEM_CHATBOX_TITLE: 'ITEM_CHATBOX_TITLE',
  ITEM_MEMBERSHIP_PERMISSION_LABEL: 'ITEM_MEMBERSHIP_PERMISSION_LABEL',
  ITEM_MEMBERSHIPS_TABLE_ACTIONS_HEADER:
    'ITEM_MEMBERSHIPS_TABLE_ACTIONS_HEADER',
  ITEM_MEMBERSHIPS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP:
    'ITEM_MEMBERSHIPS_TABLE_CANNOT_DELETE_PARENT_TOOLTIP',
  ITEM_MEMBERSHIPS_TABLE_MEMBER_HEADER: 'ITEM_MEMBERSHIPS_TABLE_MEMBER_HEADER',
  ITEM_MEMBERSHIPS_TABLE_STATUS_HEADER: 'ITEM_MEMBERSHIPS_TABLE_STATUS_HEADER',
  ITEM_MEMBERSHIPS_TABLE_PERMISSION_HEADER:
    'ITEM_MEMBERSHIPS_TABLE_PERMISSION_HEADER',
  ITEM_MENU_CREATE_SHORTCUT_MENU_ITEM: 'ITEM_MENU_CREATE_SHORTCUT_MENU_ITEM',
  ITEM_MENU_DUPLICATE_MENU_ITEM: 'ITEM_MENU_DUPLICATE_MENU_ITEM',
  ITEM_MENU_FLAG_MENU_ITEM: 'ITEM_MENU_FLAG_MENU_ITEM',
  ITEM_METADATA_CREATED_AT_TITLE: 'ITEM_METADATA_CREATED_AT_TITLE',
  ITEM_METADATA_LINK_TITLE: 'ITEM_METADATA_LINK_TITLE',
  ITEM_METADATA_SIZE_TITLE: 'ITEM_METADATA_SIZE_TITLE',
  ITEM_METADATA_TITLE: 'ITEM_METADATA_TITLE',
  ITEM_METADATA_UPDATED_AT_TITLE: 'ITEM_METADATA_UPDATED_AT_TITLE',
  ITEM_METADATA_LANGUAGE_TITLE: 'ITEM_METADATA_LANGUAGE_TITLE',
  ITEM_SEARCH_NO_RESULTS_MESSAGE: 'ITEM_SEARCH_NO_RESULTS_MESSAGE',
  ITEM_SEARCH_PLACEHOLDER: 'ITEM_SEARCH_PLACEHOLDER',
  ITEM_SETTINGS_CC_ATTRIBUTION_TITLE: 'ITEM_SETTINGS_CC_ATTRIBUTION_TITLE',
  ITEM_SETTINGS_CC_REQUIRE_ATTRIBUTION_OPTION_LABEL:
    'ITEM_SETTINGS_CC_REQUIRE_ATTRIBUTION_OPTION_LABEL',
  ITEM_SETTINGS_CC_CC0_OPTION_LABEL: 'ITEM_SETTINGS_CC_CC0_OPTION_LABEL',
  ITEM_SETTINGS_CC_COMMERCIAL_TITLE: 'ITEM_SETTINGS_CC_COMMERCIAL_TITLE',
  ITEM_SETTINGS_CC_ALLOW_COMMERCIAL_OPTION_LABEL:
    'ITEM_SETTINGS_CC_ALLOW_COMMERCIAL_OPTION_LABEL',
  ITEM_SETTINGS_CC_DISALLOW_COMMERCIAL_OPTION_LABEL:
    'ITEM_SETTINGS_CC_DISALLOW_COMMERCIAL_OPTION_LABEL',
  ITEM_SETTINGS_CC_REMIX_TITLE: 'ITEM_SETTINGS_CC_REMIX_TITLE',
  ITEM_SETTINGS_CC_ALLOW_REMIX_OPTION_LABEL:
    'ITEM_SETTINGS_CC_ALLOW_REMIX_OPTION_LABEL',
  ITEM_SETTINGS_CC_ALLOW_SHARE_ALIKE_REMIX_OPTION_LABEL:
    'ITEM_SETTINGS_CC_ALLOW_SHARE_ALIKE_REMIX_OPTION_LABEL',
  ITEM_SETTINGS_CC_DISALLOW_REMIX_OPTION_LABEL:
    'ITEM_SETTINGS_CC_DISALLOW_REMIX_OPTION_LABEL',
  ITEM_SETTINGS_CC_LICENSE_INFORMATIONS:
    'ITEM_SETTINGS_CC_LICENSE_INFORMATIONS',
  ITEM_SETTINGS_CC_LICENSE_LABEL: 'ITEM_SETTINGS_CC_LICENSE_LABEL',
  ITEM_SETTINGS_CC_LICENSE_MODAL_CONTENT:
    'ITEM_SETTINGS_CC_LICENSE_MODAL_CONTENT',
  ITEM_SETTINGS_CC_LICENSE_MODAL_TITLE: 'ITEM_SETTINGS_CC_LICENSE_MODAL_TITLE',
  ITEM_SETTINGS_CC_LICENSE_MORE_INFORMATIONS:
    'ITEM_SETTINGS_CC_LICENSE_MORE_INFORMATIONS',
  ITEM_SETTINGS_CC_LICENSE_NONE_LABEL: 'ITEM_SETTINGS_CC_LICENSE_NONE_LABEL',
  ITEM_SETTINGS_CC_LICENSE_PREVIEW_TITLE:
    'ITEM_SETTINGS_CC_LICENSE_PREVIEW_TITLE',
  ITEM_SETTINGS_CC_LICENSE_SUBMIT_BUTTON:
    'ITEM_SETTINGS_CC_LICENSE_SUBMIT_BUTTON',
  ITEM_SETTINGS_CC_LICENSE_TITLE: 'ITEM_SETTINGS_CC_LICENSE_TITLE',
  ITEM_SETTINGS_CO_EDITORS_INFORMATIONS:
    'ITEM_SETTINGS_CO_EDITORS_INFORMATIONS',
  ITEM_SETTINGS_CO_EDITORS_TITLE: 'ITEM_SETTINGS_CO_EDITORS_TITLE',
  ITEM_SETTINGS_VISIBILITY_CANNOT_EDIT_PARENT_MESSAGE:
    'ITEM_SETTINGS_VISIBILITY_CANNOT_EDIT_PARENT_MESSAGE',
  ITEM_SETTINGS_VISIBILITY_PRIVATE_INFORMATION:
    'ITEM_SETTINGS_VISIBILITY_PRIVATE_INFORMATION',
  ITEM_SETTINGS_VISIBILITY_PRIVATE_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PRIVATE_LABEL',
  ITEM_SETTINGS_VISIBILITY_HIDDEN_LABEL:
    'ITEM_SETTINGS_VISIBILITY_HIDDEN_LABEL',
  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_LABEL',
  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_AND_PASSWORD_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_AND_PASSWORD_LABEL',
  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_PSEUDONYM_LABEL',
  ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_SELECT_MESSAGE:
    'ITEM_SETTINGS_VISIBILITY_PSEUDONYMIZED_SCHEMA_SELECT_MESSAGE',
  ITEM_SETTINGS_VISIBILITY_PUBLIC_INFORMATIONS:
    'ITEM_SETTINGS_VISIBILITY_PUBLIC_INFORMATIONS',
  ITEM_SETTINGS_VISIBILITY_HIDDEN_INFORMATION:
    'ITEM_SETTINGS_VISIBILITY_HIDDEN_INFORMATION',
  ITEM_SETTINGS_VISIBILITY_PUBLIC_LABEL:
    'ITEM_SETTINGS_VISIBILITY_PUBLIC_LABEL',
  ITEM_SETTINGS_VISIBILITY_TITLE: 'ITEM_SETTINGS_VISIBILITY_TITLE',
  ITEM_TAGS_PLACEHOLDER: 'ITEM_TAGS_PLACEHOLDER',
  ITEM_TAGS_CHIP_BUTTON_EDIT: 'ITEM_TAGS_CHIP_BUTTON_EDIT',
  ITEM_TAGS_TITLE: 'ITEM_TAGS_TITLE',
  ITEM_TAGS_LABEL: 'ITEM_TAGS_LABEL',
  ITEM_TAGS_HELPER_TEXT: 'ITEM_TAGS_HELPER_TEXT',
  ITEM_TAGS_MISSING_WARNING: 'ITEM_TAGS_MISSING_WARNING',
  ITEMS_GRID_ITEMS_PER_PAGE_TITLE: 'ITEMS_GRID_ITEMS_PER_PAGE_TITLE',
  ITEMS_TABLE_ACTIONS_HEADER: 'ITEMS_TABLE_ACTIONS_HEADER',
  ITEMS_TABLE_CREATOR_HEADER: 'ITEMS_TABLE_CREATOR_HEADER',
  ITEMS_TABLE_DRAG_DEFAULT_MESSAGE: 'ITEMS_TABLE_DRAG_DEFAULT_MESSAGE',
  ITEMS_TABLE_EMPTY_MESSAGE: 'ITEMS_TABLE_EMPTY_MESSAGE',
  ITEMS_TABLE_STATUS_HEADER: 'ITEMS_TABLE_STATUS_HEADER',
  ITEMS_TABLE_NAME_HEADER: 'ITEMS_TABLE_NAME_HEADER',
  ITEMS_TABLE_SELECTION_TEXT: 'ITEMS_TABLE_SELECTION_TEXT',
  ITEMS_TABLE_TYPE_HEADER: 'ITEMS_TABLE_TYPE_HEADER',
  ITEMS_TABLE_UPDATED_AT_HEADER: 'ITEMS_TABLE_UPDATED_AT_HEADER',
  ITEMS_TREE_OWN_ITEMS_LABEL: 'ITEMS_TREE_OWN_ITEMS_LABEL',
  LAYOUT_MODE_GRID_LABEL: 'LAYOUT_MODE_GRID_LABEL',
  LAYOUT_MODE_LIST_LABEL: 'LAYOUT_MODE_LIST_LABEL',
  LIBRARY_SETTINGS_PUBLISH_BUTTON: 'LIBRARY_SETTINGS_PUBLISH_BUTTON',
  LIBRARY_SETTINGS_PUBLISH_BUTTON_DISABLED:
    'LIBRARY_SETTINGS_PUBLISH_BUTTON_DISABLED',
  LIBRARY_SETTINGS_PUBLISH_NOTIFICATIONS_LABEL:
    'LIBRARY_SETTINGS_PUBLISH_NOTIFICATIONS_LABEL',
  LIBRARY_SETTINGS_PUBLISHED_STATUS: 'LIBRARY_SETTINGS_PUBLISHED_STATUS',
  LIBRARY_SETTINGS_CHILD_PUBLISHED_STATUS:
    'LIBRARY_SETTINGS_CHILD_PUBLISHED_STATUS',
  LIBRARY_SETTINGS_TYPE_NOT_ALLOWED_STATUS:
    'LIBRARY_SETTINGS_TYPE_NOT_ALLOWED_STATUS',
  LIBRARY_SETTINGS_UNPUBLISH_BUTTON: 'LIBRARY_SETTINGS_UNPUBLISH_BUTTON',
  LIBRARY_SETTINGS_VALIDATION_CONFIGURATION_TITLE:
    'LIBRARY_SETTINGS_VALIDATION_CONFIGURATION_TITLE',
  LIBRARY_SETTINGS_VALIDATION_INFORMATIONS:
    'LIBRARY_SETTINGS_VALIDATION_INFORMATIONS',
  LIBRARY_SETTINGS_VALIDATION_PUBLICATION_TITLE:
    'LIBRARY_SETTINGS_VALIDATION_PUBLICATION_TITLE',
  LIBRARY_SETTINGS_VALIDATION_REFRESH_BUTTON:
    'LIBRARY_SETTINGS_VALIDATION_REFRESH_BUTTON',
  LIBRARY_SETTINGS_VALIDATION_STATUS_FAILURE:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_FAILURE',
  LIBRARY_SETTINGS_VALIDATION_STATUS_PENDING_AUTOMATIC:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_PENDING_AUTOMATIC',
  LIBRARY_SETTINGS_VALIDATION_STATUS_READY_TO_PUBLISH:
    'LIBRARY_SETTINGS_VALIDATION_STATUS_READY_TO_PUBLISH',
  LIBRARY_SETTINGS_VALIDATION_VALIDATE_BUTTON:
    'LIBRARY_SETTINGS_VALIDATION_VALIDATE_BUTTON',
  LIBRARY_SETTINGS_UNAUTHORIZED: 'LIBRARY_SETTINGS_UNAUTHORIZED',
  LINK_DEFAULT_NAME: 'LINK_DEFAULT_NAME',
  MOVE_ITEM_MODAL_TITLE: 'MOVE_ITEM_MODAL_TITLE',
  ITEM_SELECTION_NAVIGATION_RECENT_ITEMS:
    'ITEM_SELECTION_NAVIGATION_RECENT_ITEMS',
  ITEM_SELECTION_NAVIGATION_PARENT: 'ITEM_SELECTION_NAVIGATION_PARENT',
  SELECT_TEMPLATE_TITLE: 'SELECT_TEMPLATE_TITLE',
  MY_ITEMS_TITLE: 'MY_ITEMS_TITLE',
  NAVIGATION_BOOKMARKED_ITEMS_TITLE: 'NAVIGATION_BOOKMARKED_ITEMS_TITLE',
  NAVIGATION_PUBLISHED_ITEMS_TITLE: 'NAVIGATION_PUBLISHED_ITEMS_TITLE',
  NAVIGATION_MY_ITEMS_TITLE: 'NAVIGATION_MY_ITEMS_TITLE',
  NAVIGATION_SHARED_ITEMS_TITLE: 'NAVIGATION_SHARED_ITEMS_TITLE',
  NEW_ITEM_APP_TAB_TEXT: 'NEW_ITEM_APP_TAB_TEXT',
  NEW_ITEM_BUTTON_TOOLTIP: 'NEW_ITEM_BUTTON_TOOLTIP',
  NEW_ITEM_BUTTON_HELPER_TEXT: 'NEW_ITEM_BUTTON_HELPER_TEXT',
  NEW_ITEM_BUTTON: 'NEW_ITEM_BUTTON',
  NEW_ITEM_DOCUMENT_TAB_TEXT: 'NEW_ITEM_DOCUMENT_TAB_TEXT',
  NEW_ITEM_ETHERPAD_TAB_TEXT: 'NEW_ITEM_ETHERPAD_TAB_TEXT',
  NEW_ITEM_FILE_TAB_TEXT: 'NEW_ITEM_FILE_TAB_TEXT',
  NEW_ITEM_FOLDER_TAB_TEXT: 'NEW_ITEM_FOLDER_TAB_TEXT',
  NEW_ITEM_H5P_TAB_TEXT: 'NEW_ITEM_H5P_TAB_TEXT',
  NEW_ITEM_LINK_TAB_TEXT: 'NEW_ITEM_LINK_TAB_TEXT',
  NEW_ITEM_ZIP_TAB_TEXT: 'NEW_ITEM_ZIP_TAB_TEXT',
  SAVE_ACTIONS_TOGGLE_TOOLTIP: 'SAVE_ACTIONS_TOGGLE_TOOLTIP',
  SETTINGS_LINK_SETTINGS_INFORMATIONS: 'SETTINGS_LINK_SETTINGS_INFORMATIONS',
  SETTINGS_LINK_SETTINGS_TITLE: 'SETTINGS_LINK_SETTINGS_TITLE',
  SETTINGS_LINK_SHOW_BUTTON: 'SETTINGS_LINK_SHOW_BUTTON',
  SETTINGS_LINK_SHOW_IFRAME: 'SETTINGS_LINK_SHOW_IFRAME',
  SETTINGS_SAVE_ACTIONS: 'SETTINGS_SAVE_ACTIONS',
  SETTINGS_THUMBNAIL_SETTINGS_INFORMATIONS:
    'SETTINGS_THUMBNAIL_SETTINGS_INFORMATIONS',
  SETTINGS_THUMBNAIL_TITLE: 'SETTINGS_THUMBNAIL_TITLE',
  SHARE_ITEM_CSV_IMPORT_BUTTON: 'SHARE_ITEM_CSV_IMPORT_BUTTON',
  SHARE_ITEM_LINK_COPY_TOOLTIP: 'SHARE_ITEM_LINK_COPY_TOOLTIP',
  SHARE_ITEM_LINK_QR_CODE: 'SHARE_ITEM_LINK_QR_CODE',
  SHARED_ITEMS_TITLE: 'SHARED_ITEMS_TITLE',
  SHARED_MEMBERS_LABEL: 'SHARED_MEMBERS_LABEL',
  SHARED_MEMBERS_TOOLTIP: 'SHARED_MEMBERS_TOOLTIP',
  SHARING_AUTHENTICATED_MEMBERS_EMPTY_MESSAGE:
    'SHARING_AUTHENTICATED_MEMBERS_EMPTY_MESSAGE',
  SHARING_AUTHENTICATED_MEMBERS_TITLE: 'SHARING_AUTHENTICATED_MEMBERS_TITLE',
  SHARING_AUTHORIZED_MEMBERS_EMPTY_MESSAGE:
    'SHARING_AUTHORIZED_MEMBERS_EMPTY_MESSAGE',
  SHARING_INVITATIONS_EMPTY_MESSAGE: 'SHARING_INVITATIONS_EMPTY_MESSAGE',
  SHARING_INVITATIONS_RESEND_BUTTON: 'SHARING_INVITATIONS_RESEND_BUTTON',
  SHARING_INVITATIONS_TITLE: 'SHARING_INVITATIONS_TITLE',
  SHARING_TITLE: 'SHARING_TITLE',
  SWITCH_ACCOUNT_BUTTON_SIGNED_IN: 'SWITCH_ACCOUNT_BUTTON_SIGNED_IN',
  SWITCH_ACCOUNT_BUTTON_SIGNED_OUT: 'SWITCH_ACCOUNT_BUTTON_SIGNED_OUT',
  TABLE_ASC_SORT_LABEL: 'TABLE_ASC_SORT_LABEL',
  TABLE_DESC_SORT_LABEL: 'TABLE_DESC_SORT_LABEL',
  TABLE_SELECT_ALL_LABEL: 'TABLE_SELECT_ALL_LABEL',
  TEXT_EDITOR_PLACEHOLDER: 'TEXT_EDITOR_PLACEHOLDER',
  THUMBNAIL_SETTING_MY_THUMBNAIL_ALT: 'THUMBNAIL_SETTING_MY_THUMBNAIL_ALT',
  TREE_MODAL_CONFIRM_BUTTON: 'TREE_MODAL_CONFIRM_BUTTON',
  UPLOAD_FILE_BROWSE: 'UPLOAD_FILE_BROWSE',
  UPLOAD_FILE_DROP_TEXT: 'UPLOAD_FILE_DROP_TEXT',
  UPLOAD_FILE_INFORMATIONS: 'UPLOAD_FILE_INFORMATIONS',
  UPLOAD_FILE_LIMITATIONS_TEXT: 'UPLOAD_FILE_LIMITATIONS_TEXT',
  UPLOAD_FILE_TITLE: 'UPLOAD_FILE_TITLE',
  USER_SWITCH_SIGN_OUT_BUTTON: 'USER_SWITCH_SIGN_OUT_BUTTON',
  USER_SWITCH_SIGNED_OUT_TOOLTIP: 'USER_SWITCH_SIGNED_OUT_TOOLTIP',
  USER_SWITCH_SWITCH_USER_TEXT: 'USER_SWITCH_SWITCH_USER_TEXT',
  STATUS_TOOLTIP_IS_PINNED: 'STATUS_TOOLTIP_IS_PINNED',
  STATUS_TOOLTIP_IS_HIDDEN: 'STATUS_TOOLTIP_IS_HIDDEN',
  STATUS_TOOLTIP_IS_PUBLIC: 'STATUS_TOOLTIP_IS_PUBLIC',
  STATUS_TOOLTIP_IS_PUBLISHED: 'STATUS_TOOLTIP_IS_PUBLISHED',
  STATUS_TOOLTIP_IS_COLLAPSIBLE: 'STATUS_TOOLTIP_IS_COLLAPSIBLE',
  STATUS_TOOLTIP_SHOW_CHATBOX: 'STATUS_TOOLTIP_SHOW_CHATBOX',
  SETTINGS_FILE_SETTINGS_TITLE: 'SETTINGS_FILE_SETTINGS_TITLE',
  FALLBACK_TITLE: 'FALLBACK_TITLE',
  FALLBACK_TEXT: 'FALLBACK_TEXT',
  FALLBACK_BACK_TO_HOME: 'FALLBACK_BACK_TO_HOME',
  REPORT_A_BUG: 'REPORT_A_BUG',
  DELETE_MEMBERSHIP: 'DELETE_MEMBERSHIP',
  DELETE_MEMBERSHIP_MODAL_CONFIRM_BUTTON:
    'DELETE_MEMBERSHIP_MODAL_CONFIRM_BUTTON',
  DELETE_MEMBERSHIP_MESSAGE: 'DELETE_MEMBERSHIP_MESSAGE',
  DELETE_OWN_MEMBERSHIP_MESSAGE: 'DELETE_OWN_MEMBERSHIP_MESSAGE',
  DELETE_LAST_ADMIN_ALERT_MESSAGE: 'DELETE_LAST_ADMIN_ALERT_MESSAGE',
  APPROVE_BUTTON_TEXT: 'APPROVE_BUTTON_TEXT',
  APP_URL: 'APP_URL',
  CREATE_APP_SEARCH_FIELD_HELPER: 'CREATE_APP_SEARCH_FIELD_HELPER',
  CREATE_CUSTOM_APP: 'CREATE_CUSTOM_APP',
  CREATE_CUSTOM_APP_DESCRIPTION: 'CREATE_CUSTOM_APP_DESCRIPTION',
  DOWNGRADE_PERMISSION_TITLE: 'DOWNGRADE_PERMISSION_TITLE',
  DOWNGRADE_PERMISSION_DESCRIPTION: 'DOWNGRADE_PERMISSION_DESCRIPTION',
  CREATE_CUSTOM_APP_HELPER_TEXT: 'CREATE_CUSTOM_APP_HELPER_TEXT',
  CREATE_NEW_APP_BACK_TO_APP_LIST_BUTTON:
    'CREATE_NEW_APP_BACK_TO_APP_LIST_BUTTON',
  APP_LIST_LOADING_FAILED: 'APP_LIST_LOADING_FAILED',

  FLAG_REASON_DESCRIPTION: 'FLAG_REASON_DESCRIPTION',
  FLAG_MODAL_TITLE: 'FLAG_MODAL_TITLE',
  FLAG_MODAL_CONFIRM: 'FLAG_MODAL_CONFIRM',
  TUTORIALS: 'TUTORIALS',

  NEW_SHORT_LINK_BUTTON: 'NEW_SHORT_LINK_BUTTON',
  CONFIRM_DELETE_SHORT_LINK_TITLE: 'CONFIRM_DELETE_SHORT_LINK_TITLE',
  CONFIRM_DELETE_SHORT_LINK_MSG: 'CONFIRM_DELETE_SHORT_LINK_MSG',
  DELETE_BTN: 'DELETE_BTN',
  SAVE_BTN: 'SAVE_BTN',
  CREATE_SHORT_LINK_TITLE: 'CREATE_SHORT_LINK_TITLE',
  EDIT_SHORT_LINK_TITLE: 'EDIT_SHORT_LINK_TITLE',
  DELETE_SHORT_LINK_TITLE: 'DELETE_SHORT_LINK_TITLE',
  SHORTEN_LINK_TOOLTIP: 'SHORTEN_LINK_TOOLTIP',
  ALIAS_VALID_MSG: 'ALIAS_VALID_MSG',
  ALIAS_CHECKING_MSG: 'ALIAS_CHECKING_MSG',
  ALIAS_UNCHANGED_MSG: 'ALIAS_UNCHANGED_MSG',
  ALIAS_ALREADY_EXIST: 'ALIAS_ALREADY_EXIST',
  GENERATE_ALIAS_TOOLTIP: 'GENERATE_ALIAS_TOOLTIP',
  ALIAS_INPUT: 'ALIAS_INPUT',
  SHORT_LINK_MIN_CHARS_ERROR: 'SHORT_LINK_MIN_CHARS_ERROR',
  SHORT_LINK_MAX_CHARS_ERROR: 'SHORT_LINK_MAX_CHARS_ERROR',
  SHORT_LINK_INVALID_CHARS_ERROR: 'SHORT_LINK_INVALID_CHARS_ERROR',
  SHORT_LINK_UNKNOWN_ERROR: 'SHORT_LINK_UNKNOWN_ERROR',
  EMPTY_FOLDER_CHILDREN_FOR_THIS_ITEM: 'EMPTY_FOLDER_CHILDREN_FOR_THIS_ITEM',
  TO_FOLDER: 'TO_FOLDER',
  ROOT: 'ROOT',
  ARIA_OPEN_DRAWER: 'ARIA_OPEN_DRAWER',
  // temporary message
  "You can also find the items of this page in ''My Graasp''. This page will be unavailable soon.":
    "You can also find the items of this page in ''My Graasp''. This page will be unavailable soon.",
  BACK: 'BACK',
  UPDATE_THUMBNAIL_AT_INFO_ALERT: 'UPDATE_THUMBNAIL_AT_INFO_ALERT',
  ITEM_ACTION_INFORMATION: 'ITEM_ACTION_INFORMATION',
  FILTER_BY_TYPES_LABEL: 'FILTER_BY_TYPES_LABEL',
  SORT_BY_LABEL: 'SORT_BY_LABEL',
  ITEM_SETTINGS_GEOLOCATION_PLACEHOLDER:
    'ITEM_SETTINGS_GEOLOCATION_PLACEHOLDER',
  ITEM_SETTINGS_GEOLOCATION_NO_ADDRESS: 'ITEM_SETTINGS_GEOLOCATION_NO_ADDRESS',
  ITEM_SETTINGS_GEOLOCATION_TITLE: 'ITEM_SETTINGS_GEOLOCATION_TITLE',
  ITEM_SETTINGS_GEOLOCATION_CLEAR: 'ITEM_SETTINGS_GEOLOCATION_CLEAR',
  ITEM_SETTINGS_GEOLOCATION_EXPLANATION:
    'ITEM_SETTINGS_GEOLOCATION_EXPLANATION',
  ITEM_SETTINGS_GEOLOCATION_INHERITED_EXPLANATION:
    'ITEM_SETTINGS_GEOLOCATION_INHERITED_EXPLANATION',
  ITEM_SETTINGS_CHAT_SETTINGS_TITLE: 'ITEM_SETTINGS_CHAT_SETTINGS_TITLE',
  ITEM_SETTINGS_CLEAR_CHAT_EXPLANATION: 'ITEM_SETTINGS_CLEAR_CHAT_EXPLANATION',
  ITEM_SETTINGS_CLEAR_CHAT_BACKUP_TEXT: 'ITEM_SETTINGS_CLEAR_CHAT_BACKUP_TEXT',
  ITEM_SETTINGS_SHOW_CHAT_DISABLED_TEXT:
    'ITEM_SETTINGS_SHOW_CHAT_DISABLED_TEXT',
  ITEM_SETTINGS_SHOW_CHAT_TITLE: 'ITEM_SETTINGS_SHOW_CHAT_TITLE',
  ITEM_SETTINGS_SHOW_CHAT_ENABLED_TEXT: 'ITEM_SETTINGS_SHOW_CHAT_ENABLED_TEXT',
  ITEM_SETTINGS_RESIZE_APP_TITLE: 'ITEM_SETTINGS_RESIZE_APP_TITLE',
  ITEM_SETTINGS_RESIZABLE_DISABLED_TEXT:
    'ITEM_SETTINGS_RESIZABLE_DISABLED_TEXT',
  ITEM_SETTINGS_RESIZABLE_ENABLED_TEXT: 'ITEM_SETTINGS_RESIZABLE_ENABLED_TEXT',
  ITEM_SETTINGS_IS_PINNED_DISABLED_TEXT:
    'ITEM_SETTINGS_IS_PINNED_DISABLED_TEXT',
  ITEM_SETTINGS_IS_PINNED_TITLE: 'ITEM_SETTINGS_IS_PINNED_TITLE',
  ITEM_SETTINGS_IS_PINNED_ENABLED_TEXT: 'ITEM_SETTINGS_IS_PINNED_ENABLED_TEXT',
  ITEM_SETTINGS_IS_COLLAPSED_TITLE: 'ITEM_SETTINGS_IS_COLLAPSED_TITLE',
  ITEM_SETTINGS_IS_COLLAPSED_DISABLED_TEXT:
    'ITEM_SETTINGS_IS_COLLAPSED_DISABLED_TEXT',
  ITEM_SETTINGS_IS_COLLAPSED_ENABLED_TEXT:
    'ITEM_SETTINGS_IS_COLLAPSED_ENABLED_TEXT',
  ITEM_SETTINGS_DESCRIPTION_PLACEMENT: 'ITEM_SETTINGS_DESCRIPTION_PLACEMENT',
  ITEM_SETTINGS_DESCRIPTION_PLACEMENT_TITLE:
    'ITEM_SETTINGS_DESCRIPTION_PLACEMENT_TITLE',
  ITEM_SETTINGS_DESCRIPTION_PLACEMENT_HELPER:
    'ITEM_SETTINGS_DESCRIPTION_PLACEMENT_HELPER',
  ITEM_SETTINGS_LICENSE_TITLE: 'ITEM_SETTINGS_LICENSE_TITLE',
  CANCEL_BUTTON: 'CANCEL_BUTTON',
  CLOSE_BUTTON: 'CLOSE_BUTTON',
  ADD_BUTTON: 'ADD_BUTTON',
  UPDATE_LICENSE: 'UPDATE_LICENSE',
  ITEM_GEOLOCATION_ADVANCED_BUTTON: 'ITEM_GEOLOCATION_ADVANCED_BUTTON',
  ITEM_GEOLOCATION_ADVANCED_MODAL_TITLE:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_TITLE',
  ITEM_GEOLOCATION_ADVANCED_MODAL_DESCRIPTION:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_DESCRIPTION',
  ITEM_GEOLOCATION_ADVANCED_MODAL_LATITUDE_LABEL:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_LATITUDE_LABEL',
  ITEM_GEOLOCATION_ADVANCED_MODAL_LONGITUDE_LABEL:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_LONGITUDE_LABEL',
  ITEM_GEOLOCATION_ADVANCED_MODAL_ADDRESS_LABEL:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_ADDRESS_LABEL',
  ITEM_GEOLOCATION_ADVANCED_MODAL_SECONDARY_ADDRESS_LABEL:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_SECONDARY_ADDRESS_LABEL',
  ITEM_GEOLOCATION_ADVANCED_MODAL_SECONDARY_ADDRESS_PLACEHOLDER:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_SECONDARY_ADDRESS_PLACEHOLDER',
  ITEM_GEOLOCATION_ADVANCED_MODAL_COUNTRY_LABEL:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_COUNTRY_LABEL',
  ITEM_GEOLOCATION_ADVANCED_MODAL_ERROR:
    'ITEM_GEOLOCATION_ADVANCED_MODAL_ERROR',

  CHIPS_ALREADY_EXIST: 'CHIPS_ALREADY_EXIST',
  ITEM_STATUS_SYNCHRONIZING: 'ITEM_STATUS_SYNCHRONIZING',
  ITEM_STATUS_SYNCHRONIZED: 'ITEM_STATUS_SYNCHRONIZED',
  ITEM_STATUS_ERROR: 'ITEM_STATUS_ERROR',

  THUMBNAIL_UPLOADER_DELETE_ARIA_LABEL: 'THUMBNAIL_UPLOADER_DELETE_ARIA_LABEL',
  THUMBNAIL_UPLOADER_IMAGE_ALT: 'THUMBNAIL_UPLOADER_IMAGE_ALT',
  THUMBNAIL_UPLOADER_UPDATE_ARIA_LABEL: 'THUMBNAIL_UPLOADER_UPDATE_ARIA_LABEL',

  DEBOUNCED_TEXTFIELD_EMPTY_ERROR: 'DEBOUNCED_TEXTFIELD_EMPTY_ERROR',

  CANNOT_UPLOAD_MORE_FILES: 'CANNOT_UPLOAD_MORE_FILES',
  UPLOADING: 'UPLOADING',
  UPLOAD_H5P_BUTTON: 'UPLOAD_H5P_BUTTON',
  UPLOAD_NOTIFICATION_LOADING: 'UPLOAD_NOTIFICATION_LOADING',
  UPLOAD_NOTIFICATION_COMPLETE: 'UPLOAD_NOTIFICATION_COMPLETE',

  UPLOAD_BETWEEN_FILES: 'UPLOAD_BETWEEN_FILES',
  MOVE_WARNING: 'MOVE_WARNING',
  MOVE_IN_NON_FOLDER_ERROR_MESSAGE: 'MOVE_IN_NON_FOLDER_ERROR_MESSAGE',
  MOVE_CONFIRM_TITLE: 'MOVE_CONFIRM_TITLE',
  ITEM_SEARCH_NOTHING_FOUND: 'ITEM_SEARCH_NOTHING_FOUND',
  ITEM_SEARCH_NOTHING_FOUND_QUERY_TITLE:
    'ITEM_SEARCH_NOTHING_FOUND_QUERY_TITLE',
  ITEM_SEARCH_NOTHING_FOUND_TYPES_TITLE:
    'ITEM_SEARCH_NOTHING_FOUND_TYPES_TITLE',
  HOME_SCREEN_LOAD_MORE_BUTTON: 'HOME_SCREEN_LOAD_MORE_BUTTON',
  PUBLISHED_ITEMS_EMPTY: 'PUBLISHED_ITEMS_EMPTY',
  PUBLISHED_ITEMS_NOT_FOUND_SEARCH: 'PUBLISHED_ITEMS_NOT_FOUND_SEARCH',

  MEMBER_VALIDATION_TITLE: 'MEMBER_VALIDATION_TITLE',
  MEMBER_VALIDATION_DESCRIPTION: 'MEMBER_VALIDATION_DESCRIPTION',
  MEMBER_VALIDATION_LINK_TEXT: 'MEMBER_VALIDATION_LINK_TEXT',
  GUEST_LIMITATION_TEXT: 'GUEST_LIMITATION_TEXT',
  GUEST_SIGN_OUT_BUTTON: 'GUEST_SIGN_OUT_BUTTON',
  REDIRECTION_TEXT: 'REDIRECTION_TEXT',
  REDIRECTION_BUTTON: 'REDIRECTION_BUTTON',
  ITEM_LOGIN_HELPER_SIGN_OUT: 'ITEM_LOGIN_HELPER_SIGN_OUT',
  INVITATION_NOT_REGISTER_TEXT: 'INVITATION_NOT_REGISTER_TEXT',
  MEMBERSHIPS_REQUEST_TABLE_CREATED_AT_HEADER:
    'MEMBERSHIPS_REQUEST_TABLE_CREATED_AT_HEADER',
  USER_MANAGEMENT_MEMBERS_TAB: 'USER_MANAGEMENT_MEMBERS_TAB',
  USER_MANAGEMENT_REQUESTS_TAB: 'USER_MANAGEMENT_REQUESTS_TAB',
  EDIT_PERMISSION_DIALOG_TITLE: 'EDIT_PERMISSION_DIALOG_TITLE',
  EDIT_PERMISSION_DIALOG_SUBMIT_BUTTON: 'EDIT_PERMISSION_DIALOG_SUBMIT_BUTTON',
  EDIT_PERMISSION_CANNOT_DOWNGRADE_FROM_PARENT:
    'EDIT_PERMISSION_CANNOT_DOWNGRADE_FROM_PARENT',
  INVITATION_DELETE_TOOLTIP: 'INVITATION_DELETE_TOOLTIP',
  MEMBERSHIP_REQUEST_ACCEPT_BUTTON: 'MEMBERSHIP_REQUEST_ACCEPT_BUTTON',
  MEMBERSHIP_REQUEST_REJECT_BUTTON: 'MEMBERSHIP_REQUEST_REJECT_BUTTON',
  MEMBERSHIP_REQUESTS_TABLE_EMPTY: 'MEMBERSHIP_REQUESTS_TABLE_EMPTY',
  ENROLL_TITLE: 'ENROLL_TITLE',
  ENROLL_BUTTON: 'ENROLL_BUTTON',
  ENROLL_DESCRIPTION: 'ENROLL_DESCRIPTION',
  REQUEST_ACCESS_PENDING_TITLE: 'REQUEST_ACCESS_PENDING_TITLE',
  REQUEST_ACCESS_PENDING_DESCRIPTION: 'REQUEST_ACCESS_PENDING_DESCRIPTION',
  REQUEST_ACCESS_TITLE: 'REQUEST_ACCESS_TITLE',
  REQUEST_ACCESS_BUTTON: 'REQUEST_ACCESS_BUTTON',
  REQUEST_ACCESS_SENT_BUTTON: 'REQUEST_ACCESS_SENT_BUTTON',
  ACCESS_MANAGEMENT_TITLE: 'ACCESS_MANAGEMENT_TITLE',
  ITEM_LOGIN_SCHEMA_DISABLED_GUEST_ACCESS_MESSAGE:
    'ITEM_LOGIN_SCHEMA_DISABLED_GUEST_ACCESS_MESSAGE',
  TRASH_COUNT: 'TRASH_COUNT',
  LINK_INVALID_MESSAGE: 'LINK_INVALID_MESSAGE',
  ITEM_NAME_CANNOT_BE_EMPTY: 'ITEM_NAME_CANNOT_BE_EMPTY',
  DOCUMENT_EMPTY_MESSAGE: 'DOCUMENT_EMPTY_MESSAGE',
  DELETE_GUESTS_ALERT_TEXT: 'DELETE_GUESTS_ALERT_TEXT',
  DELETE_GUESTS_MODAL_TITLE: 'DELETE_GUESTS_MODAL_TITLE',
  DELETE_GUESTS_MODAL_DELETE_BUTTON: 'DELETE_GUESTS_MODAL_DELETE_BUTTON',
  DELETE_GUESTS_MODAL_CONTENT: 'DELETE_GUESTS_MODAL_CONTENT',
  DELETE_ITEM_LOGIN_SCHEMA_ALERT_TEXT: 'DELETE_ITEM_LOGIN_SCHEMA_ALERT_TEXT',
  CREATE_FOLDER_BUTTON_TEXT: 'CREATE_FOLDER_BUTTON_TEXT',
  TAGS_DESCRITPION: 'TAGS_DESCRITPION',
  TAGS_DISCIPLINE_HELPERTEXT: 'TAGS_DISCIPLINE_HELPERTEXT',
  TAGS_LEVEL_HELPERTEXT: 'TAGS_LEVEL_HELPERTEXT',
  TAGS_RESOURCE_TYPE_HELPERTEXT: 'TAGS_RESOURCE_TYPE_HELPERTEXT',
};
