// todo: use create routine from utils
export const COPY_MEMBER_ID_TO_CLIPBOARD = {
  SUCCESS: 'COPY_MEMBER_ID_TO_CLIPBOARD/SUCCESS',
  FAILURE: 'COPY_MEMBER_ID_TO_CLIPBOARD/FAILURE',
};

export const COPY_ITEM_LINK_TO_CLIPBOARD = {
  SUCCESS: 'COPY_ITEM_LINK_TO_CLIPBOARD/SUCCESS',
  FAILURE: 'COPY_ITEM_LINK_TO_CLIPBOARD/FAILURE',
};
