export const ITEM_LOGIN_SIGN_IN_SUCCESS = 'ITEM_LOGIN_SIGN_IN_SUCCESS';
export const FLAG_ITEM_LOGIN_SIGNING_IN = 'FLAG_ITEM_LOGIN_SIGNING_IN';
export const ITEM_LOGIN_SIGN_IN_ERROR = 'ITEM_LOGIN_SIGN_IN_ERROR';
export const PUT_ITEM_LOGIN_SUCCESS = 'PUT_ITEM_LOGIN_SUCCESS';
export const PUT_ITEM_LOGIN_ERROR = 'PUT_ITEM_LOGIN_ERROR';
