export const GET_NAVIGATION_SUCCESS = 'GET_NAVIGATION_SUCCESS';
export const GET_USER_ITEM_TREE_SUCCESS = 'GET_USER_ITEM_TREE_SUCCESS';
export const GET_CHILDREN_SUCCESS = 'GET_CHILDREN_SUCCESS';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const GET_OWN_ITEMS_SUCCESS = 'GET_OWN_ITEMS_SUCCESS';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const CLEAR_ITEM_SUCCESS = 'CLEAR_ITEM_SUCCESS';
