export const SET_MOVE_MODAL_SETTINGS = 'SET_MOVE_MODAL_SETTINGS';
export const SET_COPY_MODAL_SETTINGS = 'SET_COPY_MODAL_SETTINGS';
export const SET_EDIT_MODAL_SETTINGS = 'SET_EDIT_MODAL_SETTINGS';
export const SET_SHARE_MODAL_SETTINGS = 'SET_SHARE_MODAL_SETTINGS';
export const SET_MODE_SUCCESS = 'SET_MODE_SUCCESS';
