export const FLAG_GETTING_CURRENT_MEMBER = 'FLAG_GETTING_CURRENT_MEMBER';
export const GET_CURRENT_MEMBER_SUCCESS = 'GET_CURRENT_MEMBER_SUCCESS';
export const GET_CURRENT_MEMBER_ERROR = 'GET_CURRENT_MEMBER_ERROR';
export const FLAG_SIGNING_OUT = 'FLAG_SIGNING_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
