export const SHARE_ITEM_ERROR = 'SHARE_ITEM_ERROR';
export const SHARE_ITEM_SUCCESS = 'SHARE_ITEM_SUCCESS';
export const GET_MEMBERSHIPS_FOR_ITEM_ERROR = 'GET_MEMBERSHIPS_FOR_ITEM_ERROR';
export const GET_MEMBERSHIPS_FOR_ITEM_SUCCESS =
  'GET_MEMBERSHIPS_FOR_ITEM_SUCCESS';
