export const ITEM_DELETE_BUTTON_CLASS = 'itemDeleteButton';
export const buildItemCard = (id) => `itemCard-${id}`;
export const CREATE_ITEM_BUTTON_ID = 'createItemButton';
export const ITEM_FORM_NAME_INPUT_ID = 'newItemNameInput';
export const ITEM_FORM_TYPE_SELECT_ID = 'newItemTypeSelect';
export const ITEM_FORM_DESCRIPTION_INPUT_ID = 'newItemDescriptionInput';
export const ITEM_FORM_IMAGE_INPUT_ID = 'newItemImageInput';
export const ITEM_FORM_CONFIRM_BUTTON_ID = 'newItemConfirmButton';
export const ITEM_SCREEN_ERROR_ALERT_ID = 'itemScreenErrorAlert';
export const buildItemLink = (id) => `itemLink-${id}`;
export const NAVIGATION_HOME_LINK_ID = 'navigationHomeLink';
export const buildNavigationLink = (id) => `navigationLink-${id}`;
export const ITEM_MENU_MOVE_BUTTON_CLASS = 'itemMenuMoveButton';
export const ITEM_MENU_BUTTON_CLASS = 'itemMenuButton';
export const ITEM_MENU_COPY_BUTTON_CLASS = 'itemMenuCopyButton';
export const buildItemMenu = (id) => `itemMenu-${id}`;
export const TREE_MODAL_TREE_ID = 'treeModalTree';
export const buildTreeItemClass = (id) => `treeItem-${id}`;
export const TREE_MODAL_CONFIRM_BUTTON_ID = 'treeModalConfirmButton';
export const ITEMS_GRID_NO_ITEM_ID = 'itemsGridNoItem';
export const ITEM_MENU_EDIT_BUTTON_CLASS = 'itemMenuEditButton';
export const ITEM_MENU_SHARE_BUTTON_CLASS = 'itemMenuShareButton';
export const SHARE_ITEM_MODAL_EMAIL_INPUT_ID = 'shareItemModalEmailInput';
export const SHARE_ITEM_MODAL_PERMISSION_SELECT_ID =
  'shareItemModalPermissionSelect';
export const buildPermissionOptionId = (id) => `permission-${id}`;
export const SHARE_ITEM_MODAL_SHARE_BUTTON_ID = 'shareItemModalShareButton';
