name: sentry release
on:
  push:
    tags:  
      - '*'           # Push events to every tag not containing /
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yarn install, build
        uses: yarn && yarn build
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: graasp-builder
        with:
          environment: production
          sourcemaps: './build'
          version: ${{ github.ref }}
